development:

    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: xchannel
    pool: 5
    username: root
    password: '123'

test:

       adapter: mysql2
       encoding: utf8
       reconnect: false
       database: xchannel
       pool: 5
       username: root
       password: '123'

production:

       adapter: postgresql
       host: localhost
       database:  HEROKU_POSTGRESQL_ORANGE
       pool: 5
       username: root
       password: '123'

#  production:
#
#    adapter: postgresql
#    host: localhost
#    database:  HEROKU_POSTGRESQL_ORANGE
#    pool: 5
#    username: root
#    password:
#  #  socket: /var/run/mysqld/mysqld.sock